### ISSUE TITLE
Census Viz UI Updates

### ISSUE THREAD

**Issue by exactlyallan** [rapidsai/plotly-dash-rapids-census-demo#2]
List of tasks to clean up original census visualization:

**Needs:**
- [x] Remove Rest GPU button
- [x] Enable map box select / zoom no longer filters
- [x] Use linear scale for age histogram
- [x] Make Education / Income chart taller
- [x] Remove Plasma and Inferno colors
- [x] Move Clear all selections to "options card" upper right corner
- [x] Remove Gender filter ( see below )
- [x] Combine options to single drop down, Color By : Total Count with Maga Color Scale... Gender Count by Blues Color Scale etc.
- [x] Remove Class of Workers ( see proposed )
- [x] Updated Readme and updated install instructions 

**Proposed (Comment for Feasibility):**
- [x] Expand Class of Worker to full list, add as a full width vertical bar chart with names overlaid on bars, make height similar to small age histogram ( place below education / income chart )
- [x] Convert Education / Income chart into two full width bar charts ( similar to above )
- [x] Warning before allowing to CPU toggle with > 50 Million points 
 - [x] Fail safe / toggle for Open Street Map [Dark Matter](https://openmaptiles.org/styles/#dark-matter) theme if no mapbox token found

**Updated Titles:**
- Census Data = Census 2010 Visualization
- Selected Population = Population Count
- Configuration = Options
- US Population = Population Distribution of Individuals
- Education - Income Distribution = Education Levels by Income Distribution 
- Age = Age Distribution 
- Acknowledgements = Acknowledgements and Data Sources

**Updated Acknowledgements:**
- 2010 Population Census and 2018 ACS data used with permission from IPUMS NHGIS, University of Minnesota, www.nhgis.org ( not for redistribution )
- Base map layer provided by mapbox
- Dashboard developed with Plot.ly Dash
- Geospatial point rendering developed with Datashader
- GPU accelerated with RAPIDS cudf and cupy libraries. CPU using pandas libraries. 
- For source code visit our GitHub

**Comment by AjayThorve** [comment]
@exactlyallan what about the color scales for the 3 new bar charts? Should they have the purple scale that age has, or should they match the datashader colorscale selected from the dropdown menu

**Comment by exactlyallan** [comment]
Match bars w/ map color scale if possible. 
RE: data spike concerns by priorities:
- Fist try the optimizations to fit it un 24GB
- If not, try to move income into a binned Datashader color map
- If not, remove education filter

**Comment by AjayThorve** [comment]
About "Fail safe / toggle for Open Street Map Dark Matter theme if no mapbox token found".

Seems tricky as the chart type we are currently using is 'scattermapbox', would require a completely different implementation.

**Comment by exactlyallan** [comment]
RE: warning before toggling to CPU - just having a hover over warning would be ideal

**Comment by AjayThorve** [comment]
Implemented all features
